### ISSUE TITLE
RC1 broke ember-cli-meta-tags

### ISSUE THREAD

**Issue by jtescher** [ember-fastboot/ember-cli-fastboot#402]
This works with ember-cli-fastboot `1.0.0-beta.19` but is broken in `1.0.0-rc.1`

Example to reproduce:

```shell
$ ember new head-bug-example && cd head-bug-example
$ npm install fastboot@1.0.0-rc.6 --save-dev
$ npm install ember-cli-fastboot@1.0.0-rc.1 --save-dev
$ npm install ember-cli-meta-tags@3.1.0 --save-dev
$ ember serve
```

This now throws a type error on boot ```TypeError: _ember.default.$ is not a function
    at Object.initialize ... instance-initializers/browser/head.js:14:1```

Looks like something is loading the browser instance initializer in the fastboot env?

**Comment by danmcclain** [comment]
See https://github.com/ember-fastboot/ember-cli-fastboot/issues/387

**Comment by buschtoens** [comment]
Pretty sure that's only because of `ember-cli-head`. See also https://github.com/ronco/ember-cli-head/pull/21

**Comment by jtescher** [comment]
Ok I'll close if this is already known 👍
